package Test_Package;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;

public class Scratch_Work {
	WebDriver driver;
    @Test
	public void createproject() throws InterruptedException
	{
		 System.setProperty("webdriver.chrome.driver", "C:\\chromepath\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe");
			
			ChromeOptions options = new ChromeOptions();
			options.addArguments("--remote-allow-origin=*");
		    driver = new ChromeDriver(options);
		    driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
			driver.get("https://www.rockwellautomation.com/en-us.html");
			driver.manage().window().maximize();
			Thread.sleep(2000);
			driver.findElement(By.xpath("//div[@class='ra-global-nav-v2__icons-container']//button[@aria-label='Open search']")).click();
			Thread.sleep(2000);
			driver.findElement(By.xpath("//input[@placeholder='Search products, services, support & more']")).sendKeys("22B-E6P6C104");
			Thread.sleep(2000);
			driver.findElement(By.xpath("//button[@class='ra-global-nav-v2__search-submit new-header']")).click();
			Thread.sleep(2000);
			driver.findElement(By.xpath("//strong[text()='22B-E6P6C104']")).click();
			
//			driver.findElement(By.xpath("//input[@name='username']")).sendKeys("Atul");
//			driver.findElement(By.xpath("//input[@name='password']")).sendKeys("Atul@123");
//			driver.findElement(By.xpath("//button[@id='logInBtn_js']")).click();
//			Thread.sleep(5000);
//			WebElement menu = driver.findElement(By.xpath("//div[text()='Menu']"));
//			menu.click();
//		    WebElement project = driver.findElement(By.xpath("//a[@id='ui-id-6']"));;
//		    project.click();;
//		    WebElement createproject = driver.findElement(By.xpath("//a[@id='project-create-link']"));
//		    createproject.click();
//		    
//		    WebElement CopyAndCreate  = driver.findElement(By.xpath("//button[@id='project-copy-create-btn']"));
//		    CopyAndCreate.click();
//		    Thread.sleep(2000);
//		    WebElement selectproject = driver.findElement(By.xpath("//a[text()='test project after 6948 18feb 4.41pm']"));
//		    selectproject.click();
//		    Thread.sleep(2000);
//		    Alert alt = driver.switchTo().alert();
//		    alt.accept();
//		    WebElement customerbox = driver.findElement(By.xpath("//input[@id='project-supplier_name']"));
//		    customerbox.click();
//		    Thread.sleep(2000);
//		    WebElement selectproject = driver.findElement(By.xpath("//a[text()='(SGPS) Show Group Production Services Inc.']"));
//		    selectproject.click();	
//		    WebElement CreateNewButton = driver.findElement(By.xpath("//a[@id='addnew_project_contact']"));
//		    CreateNewButton.click();
//		    WebElement Email = driver.findElement(By.xpath("//input[@data-field-name='contact-email']"));
//		    Email.sendKeys("atul@rutamsoft.com");
//		    WebElement  Department = driver.findElement(By.xpath("//input[@data-field-name='contact-department']"));
//		    Department.sendKeys("Sooftware Testing");
//		    WebElement OfficePhone =driver.findElement(By.xpath("//input[@data-field-name='contact-office_phone']"));
//		    OfficePhone.sendKeys("9656346311");
//		    WebElement Mobile = driver.findElement(By.xpath("//input[@data-field-name='contact-mobile']"));
//		    Mobile.sendKeys("9356346311");
//		    WebElement Status = driver.findElement(By.xpath("//select[@data-field-name='contact-status']"));
//		    Select s = new Select(Status);
//		    s.selectByVisibleText("Inactive");
//		    WebElement FirstName = driver.findElement(By.xpath("//input[@data-field-name='contact-first_name']"));
//		    FirstName.sendKeys("Atul");
//		    WebElement LastName = driver.findElement(By.xpath("//input[@data-field-name='contact-last_name']"));
//		    LastName.sendKeys("Walekar");
//		    WebElement Designation = driver.findElement(By.xpath("//input[@data-field-name='contact-title']"));
//		    Designation.sendKeys("Automation Engineer");
//		    WebElement PrimaryPhone = driver.findElement(By.xpath("//input[@data-field-name='contact-phone']"));
//		    PrimaryPhone.sendKeys("9689823654");
//		    WebElement Fax = driver.findElement(By.xpath("//input[@data-field-name='contact-fax']"));
//		    Fax.sendKeys("987654321");
//		    WebElement Comments = driver.findElement(By.xpath("//textarea[@data-field-name='contact-comments']"));
//		    Comments.sendKeys("Create New Contacts");
//		    WebElement ExtraField1 = driver.findElement(By.xpath("(//a[text()='Extra Fields'])[11]"));
//		    ExtraField1.click();	
//		    WebElement Street = driver.findElement(By.xpath("//input[@data-extra_field_name='street']"));
//		    Street.sendKeys("MG Street, Pune");
//		    WebElement City = driver.findElement(By.xpath("(//input[@data-extra_field_name='city'])[2]"));
//		    City.sendKeys("Pune");
//		    WebElement StateProvince = driver.findElement(By.xpath("//input[@data-extra_field_name='state_province']"));
//		    StateProvince.sendKeys("Maharashtra");
//		    WebElement PostalCode = driver.findElement(By.xpath("//input[@data-extra_field_name='zip_postalcode']"));
//		    PostalCode.sendKeys("411039");
//		    WebElement CuntryCNCEF = driver.findElement(By.xpath("(//input[@data-extra_field_name='country'])[2]"));
//		    CuntryCNCEF.sendKeys("INDIA");
//		    WebElement maillingstreet = driver.findElement(By.xpath("//input[@data-extra_field_name='mailing_street']"));
//		    maillingstreet.sendKeys("12 Laxmi Nagar Street");
//		    WebElement maillingcity = driver.findElement(By.xpath("//input[@data-extra_field_name='mailing_city']"));
//		    maillingcity.sendKeys("Bhosari");
//		    WebElement MaillingStateProvince = driver.findElement(By.xpath("//input[@data-extra_field_name='mailing_state_province']"));
//		    MaillingStateProvince.sendKeys("Maharashtra");
//		    WebElement MaillingPostalCode = driver.findElement(By.xpath("//input[@data-extra_field_name='mailing_zip_postalcode']"));
//		    MaillingPostalCode.sendKeys("411045");
//		    WebElement MaillingCountry = driver.findElement(By.xpath("//input[@data-extra_field_name='mailing_country']"));
//		    MaillingCountry.sendKeys("INDIA");
//		    WebElement CreateNew = driver.findElement(By.xpath("(//span[text()='Create New'])[3]"));
//		    CreateNew.click();
//		    WebElement CancelCNC = driver.findElement(By.xpath("(//span[text()='Cancel'])[18]"));
//		    CancelCNC.click();
//		    
		    
		    
		    
		    
		    
//		    WebElement projectnumber = driver.findElement(By.xpath("//input[@id='project_no' and @class='edit editbox-medium form-control']"));
//		    projectnumber.clear();
//		    projectnumber.sendKeys("1895");
//		    WebElement projectname = driver.findElement(By.xpath("//input[@id='project_name' and @class='edit editbox-medium form-control']"));
//		    projectname.sendKeys("Automation/Project");
//		    WebElement customerbox = driver.findElement(By.xpath("//input[@id='project-supplier_name']"));
//		    customerbox.click();
//		    WebElement New = driver.findElement(By.xpath("(//a[@class='qp-create-new'])[9]"));
//		    New.click();
//		    Thread.sleep(5000);
//		    
//		    WebElement Name = driver.findElement(By.xpath("//input[@data-field-name='name']"));
//		    Name.sendKeys("ATUL");
//		    WebElement Phone = driver.findElement(By.xpath("//input[@data-field-name='phone']"));
//		    Phone.sendKeys("9356346311");
//		    WebElement Comments = driver.findElement(By.xpath("//textarea[@data-field-name='comments']"));
//		    Comments.sendKeys("Project For Autmation Engineer");
//		    WebElement DiscountBox = driver.findElement(By.xpath("(//input[@data-field-name='discount_segment'])[2]"));
//		    DiscountBox.click();
//		    Thread.sleep(5000);
//		    WebElement SelectDiscount = driver.findElement(By.xpath("//a[text()='Vighnahar_disc_seg']"));
//		    SelectDiscount.click();
//		    WebElement Entity = driver.findElement(By.xpath("//select[@data-field-name='entity_type']"));
//		    Select s1 = new Select(Entity);
//		    s1.selectByVisibleText("Supplier");
//		    WebElement Fax = driver.findElement(By.xpath("//input[@data-field-name='supplier-fax']"));
//		    Fax.sendKeys("12345");
//		    WebElement Status1 = driver.findElement(By.xpath("//select[@id='popup-supplier-status']"));
//		    Select s2 = new Select(Status1);
//		    s2.selectByVisibleText("Inactive");	//input[@data-field-name='supplier-address3']	    
//		    WebElement OfficeAddres1 = driver.findElement(By.xpath("//input[@data-field-name='supplier-address']"));
//		    OfficeAddres1.sendKeys("ABC");
//		    WebElement OfficeAddres3 = driver.findElement(By.xpath("//input[@data-field-name='supplier-address3']"));
//		    OfficeAddres3.sendKeys("DEF");
//		    WebElement state = driver.findElement(By.xpath("//input[@data-field-name='supplier-state']"));
//		    state.sendKeys("Maharashtra");
//		    WebElement Zip = driver.findElement(By.xpath("//input[@data-field-name='supplier-zip']"));
//		    Zip.sendKeys("411039");
//		    WebElement OfficeAddres2 = driver.findElement(By.xpath("//input[@data-field-name='supplier-address2']"));
//		    OfficeAddres2.sendKeys("GHI");
//		    WebElement City = driver.findElement(By.xpath("//input[@data-field-name='supplier-city']"));
//		    City.sendKeys("PUNE");
//		    WebElement Country = driver.findElement(By.xpath("//input[@data-field-name='supplier-country']"));
//		    Country.sendKeys("INDIA");
//		    WebElement URL = driver.findElement(By.xpath("//input[@data-field-name='supplier-url']"));
//		    URL.sendKeys("abc.com");
//		    
//		    WebElement ShippingAddres1 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_address']"));
//		    ShippingAddres1.sendKeys("ABC");
//		    WebElement ShippingAddres3 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_address3']"));
//		    ShippingAddres3.sendKeys("DEF");
//		    WebElement state1 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_state']"));
//		    state1.sendKeys("Maharashtra");
//		    WebElement Zip1 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_zip']"));
//		    Zip1.sendKeys("411039");
//		    WebElement ShippingAddres2 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_address2']"));
//		    ShippingAddres2.sendKeys("GHI");
//		    WebElement City1 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_city']"));
//		    City1.sendKeys("PUNE");
//		    WebElement Country1 = driver.findElement(By.xpath("//input[@data-field-name='supplier-shipping_country']"));
//		    Country1.sendKeys("INDIA");
//		    
//		    WebElement ExtraFields = driver.findElement(By.xpath("(//a[text()='Extra Fields'])[10]"));
//		    ExtraFields.click();
//		    Thread.sleep(2000);
//		    WebElement PaymentTerms = driver.findElement(By.xpath("//select[@data-extra_field_name='payment_terms']"));
//		    Select ss = new Select(PaymentTerms);
//		    ss.selectByVisibleText("45 Days");
//		    WebElement MobileNo = driver.findElement(By.xpath("//input[@data-extra_field_name='mobile_no']"));
//		    MobileNo.sendKeys("9659874521");
//		    WebElement Website = driver.findElement(By.xpath("//input[@data-extra_field_name='website']"));
//		    Website.sendKeys("www.website.com");
//		    WebElement ContactPersonAddress = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address']"));
//		    ContactPersonAddress.sendKeys("Bhosari Pune");
//		    WebElement ContactPersonMailingAddress = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address']"));
//		    ContactPersonMailingAddress.sendKeys("abcdef");
//		    WebElement ContactPersonPhone = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone']"));
//		    ContactPersonPhone.sendKeys("9785462512");
//		    WebElement ContactPersonMobile = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile']"));
//		    ContactPersonMobile.sendKeys("7857498666");
//		    WebElement ContactPersonEmail = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email']"));
//		    ContactPersonEmail.sendKeys("xyz@gmail.com");
//		    WebElement ContactPersonTitle = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title']"));
//		    ContactPersonTitle.sendKeys("Rutamsoft");
//		    WebElement ContactPersonName2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name2']"));
//		    ContactPersonName2.sendKeys("Sameer");
//		    WebElement ContactPersonAddress2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address2']"));
//		    ContactPersonAddress2.sendKeys("Mumbai");
//		    WebElement ContactPersonMailAddress2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address2']"));
//		    ContactPersonMailAddress2.sendKeys("Dighi");
//		    WebElement ContactPersonPhone2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone2']"));
//		    ContactPersonPhone2.sendKeys("7895694521");
//		    WebElement ContactPersonMobile2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile2']"));
//		    ContactPersonMobile2.sendKeys("9656325689");
//		    WebElement ContactPersonEmail2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email2']"));
//		    ContactPersonEmail2.sendKeys("abcdef@gmail.com");
//		    WebElement ContactPersonTitle2 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title2']"));
//		    ContactPersonTitle2.sendKeys("Rutamsoft123");
//		    WebElement ContactPersonName3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name3']"));
//		    ContactPersonName3.sendKeys("Anjali");
//		    WebElement ContactPersonAddress3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address3']"));
//		    ContactPersonAddress3.sendKeys("Dubai");
//		    WebElement ContactPersonMailAddress3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address3']"));
//		    ContactPersonMailAddress3.sendKeys("abcdefghi@gmail.com");
//		    WebElement ContactPersonPhone3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone3']"));
//		    ContactPersonPhone3.sendKeys("7548963215");
//		    WebElement ContactPersonMobile3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile3']"));
//		    ContactPersonMobile3.sendKeys("7456321586");
//		    WebElement ContactPersonEmail3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email3']"));
//		    ContactPersonEmail3.sendKeys("pqrst@gmail.com");
//		    WebElement ContactPersonTitle3 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title3']"));
//		    ContactPersonTitle3.sendKeys("Rutamsoft123");
//		    WebElement ContactPersonName4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name4']"));
//		    ContactPersonName4.sendKeys("Rahul");
//		    WebElement ContactPersonAddress4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address4']"));
//		    ContactPersonAddress4.sendKeys("Nagpur");
//		    WebElement ContactPersonMailAddress4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address4']"));
//		    ContactPersonMailAddress4.sendKeys("uvwxy@gmail.com");
//		    WebElement ContactPersonPhone4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone4']"));
//		    ContactPersonPhone4.sendKeys("9636562145");
//		    WebElement ContactPersonMobile4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile4']"));
//		    ContactPersonMobile4.sendKeys("7775798422");
//		    WebElement ContactPersonEmail4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email4']"));
//		    ContactPersonEmail4.sendKeys("ijkl@gmail.com");
//		    WebElement ContactPersonTitle4 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title4']"));
//		    ContactPersonTitle4.sendKeys("Rutamsoft567");
//		    WebElement ContactPersonName5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name5']"));
//		    ContactPersonName5.sendKeys("Ajinkya");
//		    WebElement ContactPersonAddress5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address5']"));
//		    ContactPersonAddress5.sendKeys("New Delhi");
//		    WebElement ContactPersonMailAddress5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address5']"));
//		    ContactPersonMailAddress5.sendKeys("abc5@gmail.com");
//		    WebElement ContactPersonPhone5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone5']"));
//		    ContactPersonPhone5.sendKeys("8687954215");
//		    WebElement ContactPersonMobile5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile5']"));
//		    ContactPersonMobile5.sendKeys("7485961236");
//		    WebElement ContactPersonEmail5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email5']"));
//		    ContactPersonEmail5.sendKeys("atul5@gmail.com");
//		    WebElement ContactPersonTitle5 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title5']"));
//		    ContactPersonTitle5.sendKeys("Rutamsoft8910");
//		    WebElement ContactPersonName6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name6']"));
//		    ContactPersonName6.sendKeys("Divyani");
//		    WebElement ContactPersonAddress6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address6']"));
//		    ContactPersonAddress6.sendKeys("Chennai");
//		    WebElement ContactPersonMailAddress6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address6']"));
//		    ContactPersonMailAddress6.sendKeys("abc6@gmail.com");
//		    WebElement ContactPersonPhone6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone6']"));
//		    ContactPersonPhone6.sendKeys("7584996542");
//		    WebElement ContactPersonMobile6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile6']"));
//		    ContactPersonMobile6.sendKeys("9656856985");
//		    WebElement ContactPersonEmail6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email6']"));
//		    ContactPersonEmail6.sendKeys("atul6@gmail.com");
//		    WebElement ContactPersonTitle6 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title6']"));
//		    ContactPersonTitle6.sendKeys("Rutamsoft987");
//		    WebElement ContactPersonName7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name7']"));
//		    ContactPersonName7.sendKeys("Rohan");
//		    WebElement ContactPersonAddress7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address7']"));
//		    ContactPersonAddress7.sendKeys("Banglore");
//		    WebElement ContactPersonMailAddress7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address7']"));
//		    ContactPersonMailAddress7.sendKeys("atul7@gmail.com");
//		    WebElement ContactPersonPhone7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone7']"));
//		    ContactPersonPhone7.sendKeys("7458963215");
//		    WebElement ContactPersonMobile7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile7']"));
//		    ContactPersonMobile7.sendKeys("9145223659");
//		    WebElement ContactPersonEmail7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email7']"));
//		    ContactPersonEmail7.sendKeys("atul7@gmail.com");
//		    WebElement ContactPersonTitle7 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title7']"));
//		    ContactPersonTitle7.sendKeys("Rutamsoft654");
//		    WebElement ContactPersonName8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name8']"));
//		    ContactPersonName8.sendKeys("Mansi");
//		    WebElement ContactPersonAddress8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address8']"));
//		    ContactPersonAddress8.sendKeys("Nashik");
//		    WebElement ContactPersonMailAddress8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address8']"));
//		    ContactPersonMailAddress8.sendKeys("atul8@gmail.com");
//		    WebElement ContactPersonPhone8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone8']"));
//		    ContactPersonPhone8.sendKeys("9695847458");
//		    WebElement ContactPersonMobile8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile8']"));
//		    ContactPersonMobile8.sendKeys("9325641253");
//		    WebElement ContactPersonEmail8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email8']"));
//		    ContactPersonEmail8.sendKeys("atul8@gmail.com");
//		    WebElement ContactPersonTitle8 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title8']"));
//		    ContactPersonTitle8.sendKeys("Rutamsoft321");
//		    WebElement ContactPersonName9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_name9']"));
//		    ContactPersonName9.sendKeys("Kedar");
//		    WebElement ContactPersonAddress9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_address9']"));
//		    ContactPersonAddress9.sendKeys("Aurangabad");
//		    WebElement ContactPersonMailAddress9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mail_address9']"));
//		    ContactPersonMailAddress9.sendKeys("atul9@gmail.com");
//		    WebElement ContactPersonPhone9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_phone9']"));
//		    ContactPersonPhone9.sendKeys("9863251545");
//		    WebElement ContactPersonMobile9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_mobile9']"));
//		    ContactPersonMobile9.sendKeys("9323564121");
//		    WebElement ContactPersonEmail9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_email9']"));
//		    ContactPersonEmail9.sendKeys("abc9@gnail.com");
//		    WebElement ContactPersonTitle9 = driver.findElement(By.xpath("//input[@data-extra_field_name='contact_person_title9']"));
//		    ContactPersonTitle9.sendKeys("Rutamsoft Technology");
//		    WebElement CreateNew = driver.findElement(By.xpath("(//span[text()='Create New'])[2]"));
//		    CreateNew.click();
//		    WebElement SaveAndCreateContact = driver.findElement(By.xpath("//span[text()='Save and Create Contact']"));
//		    SaveAndCreateContact.click();
//		    WebElement Cancel = driver.findElement(By.xpath("(//span[text()='Cancel'])[17]"));
//		    Cancel.click();
		    
		    
		    
//		    Thread.sleep(5000);
//		    WebElement selectproject = driver.findElement(By.xpath("//a[text()='(SGPS) Show Group Production Services Inc.']"));
//		    selectproject.click();
//		    WebElement quotation = driver.findElement(By.xpath("//select[@id='project_status']")); 
//		    Select s1 = new Select(quotation);
//		    s1.selectByVisibleText("active");
//		    Thread.sleep(1000);
//		    WebElement projectcomments = driver.findElement(By.xpath("//textarea[@id='project_comments']"));
//		    projectcomments.sendKeys("This is project for Automation");//
//		    WebElement quotatioNo = driver.findElement(By.xpath("//input[@id='quotation_no']"));
//		    quotatioNo.clear();
//		    quotatioNo.sendKeys("845911");
//		    Thread.sleep(1000);
//		    WebElement datecreatebox = driver.findElement(By.xpath("//input[@id='project_date_created']"));
//		    datecreatebox.click();
//		    Thread.sleep(5000);
//		    WebElement selectmonth1 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-month'])[2]"));
//			Select s4 = new Select(selectmonth1);
//			s4.selectByVisibleText("Jun");
//			Thread.sleep(1000);
//			WebElement selectyear1 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-year'])[2]"));
//			Select s5 = new Select(selectyear1);
//			s5.selectByValue("2025");
//			Thread.sleep(1000);
//			WebElement day1 = driver.findElement(By.xpath("(//a[text()='15'])[4]"));
//			day1.click();
//			Thread.sleep(1000);
//		    WebElement datemodifiedbox = driver.findElement(By.xpath("//input[@id='project_date']"));
//		    datemodifiedbox.click();
//		    Thread.sleep(5000);
//		    WebElement selectmonth2 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-month'])[2]"));
//			Select s6 = new Select(selectmonth2);
//			s6.selectByVisibleText("Jul");
//			Thread.sleep(1000);
//			WebElement selectyear2 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-year'])[2]"));
//			Select s7 = new Select(selectyear2);
//			s7.selectByValue("2025");
//			Thread.sleep(1000);
//			WebElement day2 = driver.findElement(By.xpath("(//a[text()='15'])[4]"));
//			day2.click();
//			Thread.sleep(1000);
//		    WebElement duedatebox = driver.findElement(By.xpath("//input[@id='project_due_date']"));
//		    duedatebox.click();
//		    Thread.sleep(5000);
//		    WebElement selectmonth3 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-month'])[2]"));
//			Select s8 = new Select(selectmonth3);
//			s8.selectByVisibleText("Aug");
//			Thread.sleep(1000);
//			WebElement selectyear3 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-year'])[2]"));
//			Select s9 = new Select(selectyear3);
//			s9.selectByValue("2025");
//			Thread.sleep(1000);
//			WebElement day3 = driver.findElement(By.xpath("(//a[text()='15'])[4]"));
//			day3.click();
//			Thread.sleep(1000);
//		    WebElement dateshippedbox = driver.findElement(By.xpath("//input[@id='project_date_shipped']"));
//		    dateshippedbox.click();
//		    Thread.sleep(5000);
//		    WebElement selectmonth4 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-month'])[2]"));
//			Select s10 = new Select(selectmonth4);
//			s10.selectByVisibleText("Sep");
//			Thread.sleep(1000);
//			WebElement selectyear4 = driver.findElement(By.xpath("(//select[@class='ui-datepicker-year'])[2]"));
//			Select s11 = new Select(selectyear4);
//			s11.selectByValue("2025");
//			Thread.sleep(1000);
//			WebElement day4 = driver.findElement(By.xpath("(//a[text()='15'])[4]"));
//			day4.click();
//			Thread.sleep(1000);
//			WebElement senddatebox = driver.findElement(By.xpath("//input[@id='project_qtn_send_date']"));
//			senddatebox.click();;
//			Thread.sleep(5000);
//			WebElement selectmonth = driver.findElement(By.xpath("(//select[@class='ui-datepicker-month'])[2]"));
//		    Select s2 = new Select(selectmonth);
//			s2.selectByVisibleText("Oct");
//		    Thread.sleep(1000);
//			WebElement selectyear = driver.findElement(By.xpath("(//select[@class='ui-datepicker-year'])[2]"));
//			Select s3 = new Select(selectyear);
//			s3.selectByValue("2025");
//		    Thread.sleep(1000);
//		    WebElement day = driver.findElement(By.xpath("(//a[text()='15'])[4]"));
//		    day.click();
//			Thread.sleep(1000);
//			WebElement salesperson = driver.findElement(By.xpath("//input[@class='edit val-extra editbox-medium form-control']"));
//			salesperson.sendKeys("Walekar Atul");
//			Thread.sleep(3000);
//			WebElement save = driver.findElement(By.xpath("//button[@id='project-save-btn']"));
//			save.click();
			
		    
		
		    
		    
		    
		    
		    
		    
		  //..................................................................Copy and Create Function	
//			CP.ClickOnCopyAndCreateButton();
//			CP.ClickOnSelectProject1Button();
//			Thread.sleep(2000);
//			CP.AcceptAlert(driver);
//			CP.DismisAlert(driver);
	//...............................................................Create New Contact Functionality
//			CP.ClickOnCustomerBox();
//			Thread.sleep(5000);
//			CP.ClickOnSelectProject();
//			Thread.sleep(2000);
//			CP.ClickOnCreateNewButtonBtnCNC();
//			CP.EnterEmailCNC();
//			CP.EnterDepartmentCNC();
//			CP.EnterOfficePhoneCNC();
//			CP.EnterMobileCNC();
//			CP.SelectStatusCNC1();
//			CP.EnterFirstNameCNC();
//			CP.EnterLastNameCNC();
//			CP.EnterDesignationCNC();
//			CP.EnterPrimaryPhoneCNC();
//			CP.EnterFax1CNC();
//			CP.EnterCommentsCNC();
//			Thread.sleep(2000);
	//...............................................................Create New Contact Extra Field Functionality		
//			CP.EnterExtraField2CNCEF();
//			CP.EnterStreetCNCEF();
//			CP.EnterCityCNCEF();
//			CP.EnterStateProvinceCNCEF();
//			CP.EnterPostalCodeCNCEF();
//			CP.EnterCuntryCNCEF();
//			CP.EntermaillingstreetCNCEF();
//			CP.EntermaillingcityCNCEF();
//			CP.EnterMaillingStateProvinceCNCEF();
//			CP.EnterMaillingPostalCodeCNCEF();
//			CP.EnterMaillingCountryCNCEF();
//			CP.ClickOnCreateNewCNCEF();
//			CP.ClickOnCancelEFCNCEF();
			
			
	//.................................................................Create Project for New customer(Business Entity Field)	
			
//			CP.ClickOnCustomerBox();
//			Thread.sleep(5000);
//			CP.ClickOnNewButton();
//			Thread.sleep(1000);
//			CP.EnterNameForCNC();
//			CP.EnterPhoneNo();
//			CP.EnterCommensForNewCustomer();
//			CP.ClikOnDiscountBox();
//			CP.SelectDiscountSegment();
//			CP.SelectEntityTypeCNC();
//			CP.EnterFaxCNC();
//			CP.SelectStatusCNC();
//			CP.EnterOfficeAddress1CNC();
//			CP.EnterOfficeAddress3CNC();
//			CP.EnterStateCNC();
//			CP.EnterZipCNC();
//			CP.EnterOfficeAddress2CNC();
//			CP.EnterCityCNC();
//			CP.EnterCountryCNC();
//			CP.EnterURLCNC();
//			CP.EnterShippingAddress4CNC();
//			CP.EnterShippingAddress5CNC();
//			CP.EnterShippingStateCNC();
//			CP.EnterShippingZipCNC();
//			CP.EnterShippingAddress6CNC();
//			CP.EnterShippingCityCNC();
//			CP.EnterShippingCountryCNC();
//			Thread.sleep(1000);
	//.................................................................Create Project for New customer(Extra Field)
//			CP.ClickOnExtraField();
//			CP.SelectPaymentTermsEF();
//			CP.EnterMobileNoEF();
//			CP.EnterWebsiteEF();
//			CP.EnterContactPersonAddressEF();
//			CP.EnterContactPersonMailingAddressEF();
//			CP.EnterContactPersonPhoneEF();
//			CP.EnterContactPersonMobileEF();
//			CP.EnterContactPersonEmailEF();
//			CP.EnterContactPersonTitleEF();
//			CP.EnterContactPersonName2EF();
//			CP.EnterContactPersonAddress2EF();
//			CP.EnterContactPersonMailAddress2EF();
//			CP.EnterContactPersonPhone2EF();
//			CP.EnterContactPersonMobile2EF();
//			CP.EnterContactPersonEmail2EF();
//			CP.EnterContactPersonTitle2EF();
//			CP.EnterContactPersonName3EF();
//			CP.EnterContactPersonAddress3EF();
//			CP.EnterContactPersonMailAddress3EF();
//			CP.EnterContactPersonPhone3EF();
//			CP.EnterContactPersonMobile3EF();
//			CP.EnterContactPersonEmail3EF();
//			CP.EnterContactPersonTitle3EF();
//			CP.EnterContactPersonName4EF();
//			CP.EnterContactPersonAddress4EF();
//			CP.EnterContactPersonMailAddress4EF();
//			CP.EnterContactPersonPhone4EF();
//			CP.EnterContactPersonMobile4EF();
//			CP.EnterContactPersonEmail4EF();
//			CP.EnterContactPersonTitle4EF();
//			CP.EnterContactPersonName5EF();
//			CP.EnterContactPersonAddress5EF();
//			CP.EnterContactPersonMailAddress5EF();
//			CP.EnterContactPersonPhone5EF();
//			CP.EnterContactPersonMobile5EF();
//			CP.EnterContactPersonEmail5EF();
//			CP.EnterContactPersonTitle5EF();
//			CP.EnterContactPersonName6EF();
//			CP.EnterContactPersonAddress6EF();
//			CP.EnterContactPersonMailAddress6EF();
//			CP.EnterContactPersonPhone6EF();
//			CP.EnterContactPersonMobile6EF();
//			CP.EnterContactPersonEmail6EF();
//			CP.EnterContactPersonTitle6EF();
//			CP.EnterContactPersonName7EF();
//			CP.EnterContactPersonAddress7EF();
//			CP.EnterContactPersonMailAddress7EF();
//			CP.EnterContactPersonPhone7EF();
//			CP.EnterContactPersonMobile7EF();
//			CP.EnterContactPersonEmail7EF();
//			CP.EnterContactPersonTitle7EF();
//			CP.EnterContactPersonName8EF();
//			CP.EnterContactPersonAddress8EF();
//			CP.EnterContactPersonMailAddress8EF();
//			CP.EnterContactPersonPhone8EF();
//			CP.EnterContactPersonMobile8EF();
//			CP.EnterContactPersonEmail8EF();
//			CP.EnterContactPersonTitle8EF();
//			CP.EnterContactPersonName9EF();
//			CP.EnterContactPersonAddress9EF();
//			CP.EnterContactPersonMailAddress9EF();
//			CP.EnterContactPersonPhone9EF();
//			CP.EnterContactPersonMobile9EF();
//			CP.EnterContactPersonEmail9EF();
//			CP.EnterContactPersonTitle9EF();
	//..............................................................................Save, SaveAndCreateContact and Cancel Function			
//			CP.ClickOnCreateNewBtnEF();
//			CP.ClickOnSaveAndCreateContactBtnEF();
//			CP.ClickOnCancelBtnEF();
	}
}
