package Test_Package;

import java.io.IOException;

import org.apache.poi.EncryptedDocumentException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import POM_Package.Create_PO_POM;
import POM_Package.Login_Quoteplan;
import POM_Package.Logout_Quoteplan;
import Utility_Package.Utility_Class_PO;


public class Test_Class_Create_PO {
	WebDriver driver;
	Create_PO_POM cpo;
	
	
	@BeforeClass
	public void openbrowser() throws InterruptedException
	{
		 System.setProperty("webdriver.chrome.driver", "C:\\Users\\Admin\\Desktop\\chromepath\\chromedriver-win64 (1)\\chromedriver-win64\\chromedriver.exe");
			System.out.println("Walekar Atul 123");
			ChromeOptions options = new ChromeOptions();
			options.addArguments("--remote-allow-origin=*");
		    driver = new ChromeDriver(options);
//	        driver = new ChromeDriver();
			driver.get("http://localhost/QuotePlan/quotep7_apqengineering/home/login");
			driver.manage().window().maximize();
		    Thread.sleep(1000);
	}
	@BeforeMethod
	public void LoginFunction() throws EncryptedDocumentException, IOException, InterruptedException
	{
		Login_Quoteplan log = new Login_Quoteplan(driver);
		log.EnterUsername(Utility_Class_PO.GetExcelsheetDataPO("PO", 2, 1));
		log.EnterPassword(Utility_Class_PO.GetExcelsheetDataPO("PO", 3, 1));
		log.ClickOnLogin();
		Thread.sleep(1000);
	    cpo = new Create_PO_POM(driver);
	}
	@Test(priority=1)
	public void CreatePO_Vpel() throws IOException, InterruptedException
	{
		String TCName = " CreatePO_Vpel ";
		String TCName3 = " Messages Tab Functionality ";
		String TCName1 = " PO History Functionality ";
		String TCName2 = " Search Functionality ";
		String TCName4 = " Edit button Functionality ";
		cpo.ClickOnMenu();
		Thread.sleep(1000);
		cpo.ClickOnPurchaseOrder();
		Thread.sleep(1000);
		cpo.ClickOnCreatePO();
		Thread.sleep(2000);
		cpo.ClickOnSelectFormatbtn();
		Thread.sleep(2000);
		cpo.ClickOnVpel();
		Thread.sleep(2000);
		cpo.ClickOnSuppliersearchbox();
		Thread.sleep(1000);
		cpo.SelectSupplier();
		Thread.sleep(1000);
		cpo.SelectContacts();
		Thread.sleep(1000);
		cpo.ClickOnProjectsearchbox();
		Thread.sleep(1000);
		cpo.SelectProject();
		Thread.sleep(1000);
		cpo.EnterPaymentTerms(Utility_Class_PO.GetExcelsheetDataPO("PO", 4, 1));
		Thread.sleep(1000);
		cpo.EnterPOComments();
		Thread.sleep(2000);
		cpo.ClickonPOExpectedDatebox();
		Thread.sleep(2000);
		cpo.ClickonPOExpDate();
		Thread.sleep(2000);
		cpo.ClickonExtraFieldsTab();
		Thread.sleep(1000);
		cpo.EnterRefJobNo(Utility_Class_PO.GetExcelsheetDataPO("PO", 5, 1));
		Thread.sleep(1000);
		cpo.SelectFreight();
		Thread.sleep(1000);
		cpo.EnterWarrantyTerms(Utility_Class_PO.GetExcelsheetDataPO("PO", 6, 1));
		Thread.sleep(1000);
		cpo.EnterContactPerson(Utility_Class_PO.GetExcelsheetDataPO("PO", 7, 1));
		Thread.sleep(1000);
		cpo.EnterMobileNo(Utility_Class_PO.GetExcelsheetDataPO("PO", 8, 1));
		Thread.sleep(1000);
		cpo.EnterEmail(Utility_Class_PO.GetExcelsheetDataPO("PO", 9, 1));
		Thread.sleep(1000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(1000);
		cpo.DraganddropPO(driver);
		Thread.sleep(1000);
		cpo.DraganddropPO1(driver);
		Thread.sleep(1000);
		cpo.ClickonTogglebtn();
		Thread.sleep(1000);
		cpo.EnterPOQty1(Utility_Class_PO.GetExcelsheetDataPO("PO", 10, 1));
		Thread.sleep(1000);
		cpo.EnterPOQty2(Utility_Class_PO.GetExcelsheetDataPO("PO", 11, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice1(Utility_Class_PO.GetExcelsheetDataPO("PO", 12, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice2(Utility_Class_PO.GetExcelsheetDataPO("PO", 13, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount1(Utility_Class_PO.GetExcelsheetDataPO("PO", 14, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount2(Utility_Class_PO.GetExcelsheetDataPO("PO", 15, 1));
		Thread.sleep(1000);
		cpo.ClickonPODueDate1box();
		Thread.sleep(1000);
		cpo.ClickonPODueDate11();
		Thread.sleep(1000);
		cpo.ClickonPODueDate33box();
		Thread.sleep(1000);
		cpo.ClickonPODueDate22();
		Thread.sleep(1000);
		cpo.EnterCGST1(Utility_Class_PO.GetExcelsheetDataPO("PO", 16, 1));
		Thread.sleep(1000);
		cpo.EnterCGST2(Utility_Class_PO.GetExcelsheetDataPO("PO", 17, 1));
		Thread.sleep(1000);
		cpo.ClickonSavePObtn();
		Thread.sleep(15000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName);
	    System.out.println("PO create and Save successfully");
	    cpo.ClickonMessagesTab();
	    Thread.sleep(1000);
	    cpo.ClickonMessagesTo();
	    Thread.sleep(1000);
	    cpo.ClickonUser();
	    Thread.sleep(1000);
	    cpo.EnterMessage();
	    Thread.sleep(1000);
	    cpo.ClickonSendbtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName3);
	    System.out.println("Message send successfully");
	    cpo.ClickonPO_HistoryTab();
	    Thread.sleep(1000);
	    cpo.ClickonTogglebtn();
	    Thread.sleep(7000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName1);
	    System.out.println("PO History Tab showing successfully");
	    cpo.ClickonEditbtn();
	    Thread.sleep(1000);
	    cpo.ClickonItemsFieldsTab();
	    Thread.sleep(1000);
	    cpo.EnterPOEditQty(Utility_Class_PO.GetExcelsheetDataPO("PO", 18, 1));
	    Thread.sleep(1000);
	    cpo.ClickonSavePObtn();
	    Thread.sleep(15000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName4);
	    System.out.println("Edit button work successfully");
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.EnterGenericSearchbox(Utility_Class_PO.GetExcelsheetDataPO("PO", 19, 1));
		Thread.sleep(1000);
		cpo.ClickonGenericSearchbtn();
		Thread.sleep(1000);
		System.out.println("Run successfully");
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName2);
	    System.out.println("Search functionality works successfully");	
	}
	@Test(priority=2)
	public void Copy_From_PO() throws IOException, InterruptedException
	{
		String TCName1 = " Copy_From_PO Functionality ";
		String TCName2 = " Trash Button Functionality ";
		cpo.ClickOnMenu();
		Thread.sleep(1000);
		cpo.ClickOnPurchaseOrder();
		Thread.sleep(2000);
		cpo.ClickOnCreatePO();
		Thread.sleep(2000);
		cpo.ClickonCopyFromPObtn();
		Thread.sleep(7000);
		cpo.ClickonExistinPO();                  //-------------Vpel
//		cpo.ClickonExistinPOApq();               //-----------APQ
//		cpo.ClickonExistinPOSurecontrols();      //-----------Surecontrols
//		cpo.ClickonExistinPOTxautosys();         //-----------Txautosys
//		cpo.ClickonExistinPODascan();            //-----------Dascan
//		Thread.sleep(2000);
//		cpo.EnterPONo(Utility_Class_PO.GetExcelsheetDataPO("PO", 21, 1)); //-----------Dascan
		Thread.sleep(1000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.EnterPOEditQty1(Utility_Class_PO.GetExcelsheetDataPO("PO", 20, 1));
	    Thread.sleep(1000);
	    cpo.ClickonSavePObtn();
		Thread.sleep(15000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName1);
		System.out.println("Copy_From_PO work successfully");
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonEditbtn();
		Thread.sleep(2000);
		cpo.DraganddropPO2(driver);
		Thread.sleep(2000);
		cpo.ClickonDeleteYesbtn();
		Thread.sleep(1000);
	    cpo.ClickonSavePObtn();
		Thread.sleep(10000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName2);
		System.out.println("Trash button work successfully");
	}
	@Test(priority=3)
	public void CreatePO_APQ() throws IOException, InterruptedException
	{
		String TCName = " CreatePO_APQ ";
		String TCName3 = " Messages Tab Functionality ";
		String TCName1 = " PO History Functionality ";
		String TCName2 = " Search Functionality ";
		String TCName4 = " Edit button Functionality ";
		cpo.ClickOnMenu();
		Thread.sleep(1000);
		cpo.ClickOnPurchaseOrder();
		Thread.sleep(1000);
		cpo.ClickOnCreatePO();
		Thread.sleep(2000);
		cpo.ClickOnSuppliersearchbox();
		Thread.sleep(1000);
		cpo.SelectSupplierAPQ();
		Thread.sleep(2000);
		cpo.SelectContactsAPQ();
		Thread.sleep(2000);
		cpo.ClickOnProjectsearchbox();
		Thread.sleep(2000);
		cpo.SelectProjectAPQ();
		Thread.sleep(5000);
		cpo.EnterPaymentTerms(Utility_Class_PO.GetExcelsheetDataPO("PO", 4, 1));
		Thread.sleep(1000);
		cpo.EnterPOComments();
		Thread.sleep(2000);
		cpo.ClickonPOExpectedDatebox();
		Thread.sleep(2000);
		cpo.ClickonPOExpDateAPQ();
		Thread.sleep(2000);
		cpo.ClickonExtraFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonPOSelectAddressAPQbtn();
		Thread.sleep(2000);
		cpo.SelectAddressNameAPQ();
		Thread.sleep(1000);
		cpo.EnterVendorNotes();
		Thread.sleep(1000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(1000);
		cpo.DraganddropPO(driver);
		Thread.sleep(1000);
		cpo.DraganddropPO1(driver);
		Thread.sleep(1000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.ClickonPOSelectTask1btn();
		Thread.sleep(2000);
		cpo.SelectTask1APQ();
		Thread.sleep(2000);
		cpo.ClickonPOSelectTask2btn();
		Thread.sleep(2000);
		cpo.SelectTask2APQ();
		Thread.sleep(2000);
		cpo.EnterPOQty1(Utility_Class_PO.GetExcelsheetDataPO("PO", 10, 1));
		Thread.sleep(1000);
		cpo.EnterPOQty2(Utility_Class_PO.GetExcelsheetDataPO("PO", 11, 1));
		Thread.sleep(1000);
		cpo.EnterExtraNotes1();
		Thread.sleep(1000);
		cpo.EnterExtraNotes2();
		Thread.sleep(1000);
		cpo.EnterUnitPrice1(Utility_Class_PO.GetExcelsheetDataPO("PO", 12, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice2(Utility_Class_PO.GetExcelsheetDataPO("PO", 13, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount1(Utility_Class_PO.GetExcelsheetDataPO("PO", 14, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount2(Utility_Class_PO.GetExcelsheetDataPO("PO", 15, 1));
		Thread.sleep(1000);
		cpo.ClickonPODueDate1box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateAPQ1();
		Thread.sleep(2000);
		cpo.ClickonPODueDate33box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateAPQ2();
		Thread.sleep(1000);
		cpo.ClickonSavePObtn();
		Thread.sleep(10000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName);
	    System.out.println("PO create and Save successfully");
	    cpo.ClickonMessagesTab();
	    Thread.sleep(1000);
	    cpo.ClickonMessagesTo();
	    Thread.sleep(1000);
	    cpo.ClickonUser();
	    Thread.sleep(1000);
	    cpo.EnterMessage();
	    Thread.sleep(1000);
	    cpo.ClickonSendbtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName3);
	    System.out.println("Message send successfully");
	    cpo.ClickonPO_HistoryTab();
	    Thread.sleep(1000);
	    cpo.ClickonTogglebtn();
	    Thread.sleep(7000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName1);
	    System.out.println("PO History Tab showing successfully");
	    cpo.ClickonEditbtn();
	    Thread.sleep(1000);
	    cpo.ClickonItemsFieldsTab();
	    Thread.sleep(1000);
	    cpo.EnterPOEditQty(Utility_Class_PO.GetExcelsheetDataPO("PO", 18, 1));
	    Thread.sleep(1000);
	    cpo.ClickonSavePObtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName4);
	    System.out.println("Edit button work successfully");
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.EnterGenericSearchbox(Utility_Class_PO.GetExcelsheetDataPO("PO", 19, 1));
		Thread.sleep(1000);
		cpo.ClickonGenericSearchbtn();
		Thread.sleep(1000);
		System.out.println("Run successfully");
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName2);
	    System.out.println("Search functionality works successfully");	
	}
	@Test(priority=4)
	public void CreatePO_Surecontrols() throws IOException, InterruptedException
	{
		String TCName = " CreatePO_Surecontrols ";
		String TCName3 = " Messages Tab Functionality ";
		String TCName1 = " PO History Functionality ";
		String TCName2 = " Search Functionality ";
		String TCName4 = " Edit button Functionality ";
		cpo.ClickOnMenu();
		Thread.sleep(1000);
		cpo.ClickOnPurchaseOrder();
		Thread.sleep(1000);
		cpo.ClickOnCreatePO();
		Thread.sleep(2000);
		cpo.ClickOnSuppliersearchbox();
		Thread.sleep(1000);
		cpo.SelectSupplierSurecontrol();
		Thread.sleep(1000);
//		cpo.SelectContactsAPQ();
//		Thread.sleep(1000);
		cpo.ClickOnProjectsearchbox();
		Thread.sleep(2000);
		cpo.SelectProjectSurecontrol();
		Thread.sleep(5000);
		cpo.EnterPaymentTerms(Utility_Class_PO.GetExcelsheetDataPO("PO", 4, 1));
		Thread.sleep(1000);
		cpo.EnterPOComments();
		Thread.sleep(2000);
		cpo.ClickonPOExpectedDatebox();
		Thread.sleep(2000);
		cpo.ClickonPOExpDateAPQ();
		Thread.sleep(2000);
		cpo.ClickonExtraFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonPOSelectAddressAPQbtn();
		Thread.sleep(2000);
		cpo.SelectAddressNameSurecontrols();
		Thread.sleep(1000);
		cpo.EnterVendorNotes1();
		Thread.sleep(1000);
		cpo.EnterTax(Utility_Class_PO.GetExcelsheetDataPO("PO", 16, 1));
		Thread.sleep(1000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(1000);
		cpo.DraganddropPO(driver);
		Thread.sleep(1000);
		cpo.DraganddropPO1(driver);
		Thread.sleep(1000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		Thread.sleep(2000);
		cpo.EnterPOQty1(Utility_Class_PO.GetExcelsheetDataPO("PO", 10, 1));
		Thread.sleep(1000);
		cpo.EnterPOQty2(Utility_Class_PO.GetExcelsheetDataPO("PO", 11, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice1(Utility_Class_PO.GetExcelsheetDataPO("PO", 12, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice2(Utility_Class_PO.GetExcelsheetDataPO("PO", 13, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount1(Utility_Class_PO.GetExcelsheetDataPO("PO", 14, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount2(Utility_Class_PO.GetExcelsheetDataPO("PO", 15, 1));
		Thread.sleep(1000);
		cpo.ClickonPODueDate1box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateAPQ1();
		Thread.sleep(2000);
		cpo.ClickonPODueDate33box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateAPQ2();
		Thread.sleep(1000);
		cpo.EnterSCItemNO1();
		Thread.sleep(1000);
		cpo.EnterSCItemNO2();
		Thread.sleep(1000);
		cpo.ClickonSavePObtn();
		Thread.sleep(10000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName);
	    System.out.println("PO create and Save successfully");
	    cpo.ClickonMessagesTab();
	    Thread.sleep(1000);
	    cpo.ClickonMessagesTo();
	    Thread.sleep(1000);
	    cpo.ClickonUser();
	    Thread.sleep(1000);
	    cpo.EnterMessage();
	    Thread.sleep(1000);
	    cpo.ClickonSendbtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName3);
	    System.out.println("Message send successfully");
	    cpo.ClickonPO_HistoryTab();
	    Thread.sleep(1000);
	    cpo.ClickonTogglebtn();
	    Thread.sleep(7000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName1);
	    System.out.println("PO History Tab showing successfully");
	    cpo.ClickonEditbtn();
	    Thread.sleep(1000);
	    cpo.ClickonItemsFieldsTab();
	    Thread.sleep(1000);
	    cpo.EnterPOEditQty(Utility_Class_PO.GetExcelsheetDataPO("PO", 18, 1));
	    Thread.sleep(1000);
	    cpo.ClickonSavePObtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName4);
	    System.out.println("Edit button work successfully");
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.EnterGenericSearchbox(Utility_Class_PO.GetExcelsheetDataPO("PO", 19, 1));
		Thread.sleep(1000);
		cpo.ClickonGenericSearchbtn();
		Thread.sleep(1000);
		System.out.println("Run successfully");
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName2);
	    System.out.println("Search functionality works successfully");	
	}
	@Test(priority=5)
	public void CreatePO_Dascan() throws IOException, InterruptedException
	{
		String TCName = " CreatePO_Dascan";
		String TCName3 = " Messages Tab Functionality ";
		String TCName1 = " PO History Functionality ";
		String TCName2 = " Search Functionality ";
		String TCName4 = " Edit button Functionality ";
		Thread.sleep(3000);
		cpo.ClickOnMenu();
		Thread.sleep(1000);
		cpo.ClickOnPurchaseOrder();
		Thread.sleep(1000);
		cpo.ClickOnCreatePO();
		Thread.sleep(2000);
		cpo.EnterPONo(Utility_Class_PO.GetExcelsheetDataPO("PO", 5, 1));
		Thread.sleep(1000);
		cpo.ClickOnSuppliersearchbox();
		Thread.sleep(1000);
		cpo.SelectSupplierSupplierDascan();
		Thread.sleep(1000);
//		cpo.SelectContactsAPQ();
//		Thread.sleep(1000);
		cpo.ClickOnProjectsearchbox();
		Thread.sleep(2000);
		cpo.SelectProjectDascan();
		Thread.sleep(7000);
		cpo.EnterPaymentTerms(Utility_Class_PO.GetExcelsheetDataPO("PO", 4, 1));
		Thread.sleep(1000);
		cpo.EnterPOComments();
		Thread.sleep(2000);
		cpo.ClickonPOExpectedDatebox();
		Thread.sleep(2000);
		cpo.ClickonPOExpDateDascan();
		Thread.sleep(2000);
		cpo.ClickonExtraFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonPOSelectAddressAPQbtn();
		Thread.sleep(2000);
		cpo.SelectAddressNameDascan();
		Thread.sleep(1000);
		cpo.EnterVendorQuote();
		Thread.sleep(1000);
		cpo.EnterTax1(Utility_Class_PO.GetExcelsheetDataPO("PO", 16, 1));
		Thread.sleep(1000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(1000);
		cpo.DraganddropPODasan(driver);
		Thread.sleep(1000);
		cpo.DraganddropPODascan1(driver);
		Thread.sleep(1000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.ClickonPOSelectTaskDascanbtn();
		Thread.sleep(2000);
		cpo.SelectTaskDasacn1();
		Thread.sleep(2000);
		cpo.ClickonPOSelectTaskDascan1btn();
		Thread.sleep(2000);
		cpo.SelectTaskDasacn2();
		Thread.sleep(2000);
		cpo.EnterPOQty1(Utility_Class_PO.GetExcelsheetDataPO("PO", 10, 1));
		Thread.sleep(1000);
		cpo.EnterPOQty2(Utility_Class_PO.GetExcelsheetDataPO("PO", 11, 1));
		Thread.sleep(1000);
		cpo.EnterExtraNotes1();
		Thread.sleep(1000);
		cpo.EnterExtraNotes2();
		Thread.sleep(1000);
		cpo.EnterUnitPrice1(Utility_Class_PO.GetExcelsheetDataPO("PO", 12, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice2(Utility_Class_PO.GetExcelsheetDataPO("PO", 13, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount1(Utility_Class_PO.GetExcelsheetDataPO("PO", 14, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount2(Utility_Class_PO.GetExcelsheetDataPO("PO", 15, 1));
		Thread.sleep(1000);
		cpo.ClickonPODueDate1box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateAPQ1();
		Thread.sleep(2000);
		cpo.ClickonPODueDate33box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateAPQ2();
		Thread.sleep(1000);
		cpo.ClickonSavePObtn();
		Thread.sleep(10000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName);
	    System.out.println("PO create and Save successfully");
	    cpo.ClickonMessagesTab();
	    Thread.sleep(1000);
	    cpo.ClickonMessagesTo();
	    Thread.sleep(1000);
	    cpo.ClickonUser();
	    Thread.sleep(1000);
	    cpo.EnterMessage();
	    Thread.sleep(1000);
	    cpo.ClickonSendbtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName3);
	    System.out.println("Message send successfully");
	    cpo.ClickonPO_HistoryTab();
	    Thread.sleep(1000);
	    cpo.ClickonTogglebtn();
	    Thread.sleep(7000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName1);
	    System.out.println("PO History Tab showing successfully");
	    cpo.ClickonEditbtn();
	    Thread.sleep(1000);
	    cpo.ClickonItemsFieldsTab();
	    Thread.sleep(1000);
	    cpo.EnterPOEditQty(Utility_Class_PO.GetExcelsheetDataPO("PO", 18, 1));
	    Thread.sleep(1000);
	    cpo.ClickonSavePObtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName4);
	    System.out.println("Edit button work successfully");
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.EnterGenericSearchbox(Utility_Class_PO.GetExcelsheetDataPO("PO", 19, 1));
		Thread.sleep(1000);
		cpo.ClickonGenericSearchbtn();
		Thread.sleep(1000);
		System.out.println("Run successfully");
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName2);
	    System.out.println("Search functionality works successfully");	
	}
	@Test(priority=6)
	public void CreatePO_Txautosys() throws IOException, InterruptedException
	{
		String TCName = " CreatePO_Txautosys";
		String TCName3 = " Messages Tab Functionality ";
		String TCName1 = " PO History Functionality ";
		String TCName2 = " Search Functionality ";
		String TCName4 = " Edit button Functionality ";
		Thread.sleep(3000);
		cpo.ClickOnMenu();
		Thread.sleep(1000);
		cpo.ClickOnPurchaseOrder();
		Thread.sleep(1000);
		cpo.ClickOnCreatePO();
		Thread.sleep(10000);
		cpo.ClickOnSuppliersearchbox();
		Thread.sleep(8000);
		cpo.SelectSupplierTxautosys();
		Thread.sleep(2000);
		cpo.SelectContactsTxautosys();
		Thread.sleep(1000);
		cpo.ClickOnProjectsearchbox();
		Thread.sleep(6000);
		cpo.SelectProjectTxautosys();
		Thread.sleep(3000);
		cpo.EnterPaymentTerms(Utility_Class_PO.GetExcelsheetDataPO("PO", 4, 1));
		Thread.sleep(1000);
		cpo.EnterPOComments();
		Thread.sleep(2000);
		cpo.ClickonPOExpectedDatebox();
		Thread.sleep(2000);
		cpo.ClickonPOExpDateTxautosys();
		Thread.sleep(2000);
		cpo.ClickonExtraFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonPOSelectAddressAPQbtn();
		Thread.sleep(2000);
		cpo.SelectAddressNameTxautosys();
		Thread.sleep(1000);
		cpo.EnterVendorNoteTxautosys();
		Thread.sleep(1000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(1000);
		cpo.DraganddropPO(driver);
		Thread.sleep(1000);
		cpo.DraganddropPO1(driver);
		Thread.sleep(1000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.ClickonPOSelectTaskDascanbtn();
		Thread.sleep(2000);
		cpo.SelectTaskTxautosys1();
		Thread.sleep(2000);
		cpo.ClickonPOSelectTaskDascan1btn();
		Thread.sleep(2000);
		cpo.SelectTaskTxautosys2();
		Thread.sleep(2000);
		cpo.EnterPOQty1(Utility_Class_PO.GetExcelsheetDataPO("PO", 10, 1));
		Thread.sleep(1000);
		cpo.EnterPOQty2(Utility_Class_PO.GetExcelsheetDataPO("PO", 11, 1));
		Thread.sleep(1000);
		cpo.EnterExtraNotes1();
		Thread.sleep(1000);
		cpo.EnterExtraNotes2();
		Thread.sleep(1000);
		cpo.EnterUnitPrice1(Utility_Class_PO.GetExcelsheetDataPO("PO", 12, 1));
		Thread.sleep(1000);
		cpo.EnterUnitPrice2(Utility_Class_PO.GetExcelsheetDataPO("PO", 13, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount1(Utility_Class_PO.GetExcelsheetDataPO("PO", 14, 1));
		Thread.sleep(1000);
		cpo.EnterDiscount2(Utility_Class_PO.GetExcelsheetDataPO("PO", 15, 1));
		Thread.sleep(1000);
		cpo.ClickonPODueDate1box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateTxautosys1();
		Thread.sleep(2000);
		cpo.ClickonPODueDate33box();
		Thread.sleep(2000);
		cpo.ClickonPODueDateTxautosys2();
		Thread.sleep(1000);
		cpo.ClickonSavePObtn();
		Thread.sleep(35000);
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName);
	    System.out.println("PO create and Save successfully");
		Thread.sleep(10000);
	    cpo.ClickonMessagesTab();
	    Thread.sleep(2000);
	    cpo.ClickonMessagesTo();
	    Thread.sleep(2000);
	    cpo.ClickonUser();
	    Thread.sleep(2000);
	    cpo.EnterMessage();
	    Thread.sleep(2000);
	    cpo.ClickonSendbtn();
	    Thread.sleep(10000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName3);
	    System.out.println("Message send successfully");
	    cpo.ClickonPO_HistoryTab();
	    Thread.sleep(1000);
	    cpo.ClickonTogglebtn();
	    Thread.sleep(5000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName1);
	    System.out.println("PO History Tab showing successfully");
	    cpo.ClickonEditbtn();
	    Thread.sleep(2000);
	    cpo.ClickonItemsFieldsTab();
	    Thread.sleep(2000);
	    cpo.EnterPOEditQty(Utility_Class_PO.GetExcelsheetDataPO("PO", 18, 1));
	    Thread.sleep(2000);
	    cpo.ClickonSavePObtn();
	    Thread.sleep(35000);
	    Utility_Class_PO.TakesscreeenshotPO(driver, TCName4);
	    System.out.println("Edit button work successfully");
	    Thread.sleep(10000);
		cpo.ClickonItemsFieldsTab();
		Thread.sleep(2000);
		cpo.ClickonTogglebtn();
		Thread.sleep(2000);
		cpo.EnterGenericSearchbox(Utility_Class_PO.GetExcelsheetDataPO("PO", 19, 1));
		Thread.sleep(2000);
		cpo.ClickonGenericSearchbtn();
		Thread.sleep(2000);
		System.out.println("Run successfully");
		Utility_Class_PO.TakesscreeenshotPO(driver, TCName2);
	    System.out.println("Search functionality works successfully");	
	    System.out.println(" My Second Changes");
	    System.out.println(" My third Changes");
	}
	@AfterMethod
	public void LogoutFunction()
	{
		Logout_Quoteplan log = new Logout_Quoteplan(driver);
		log.clickonadminprofile();
		log.clickonlogoutbtn();
		
	}
	@AfterClass
	public void Closebrowser()
	{
		driver.close();
	}

}
